### ISSUE TITLE
Repeat doesn't work for m1>200 in PRNG approach

### ISSUE THREAD

**Issue by IVN-tone** [zhinst/blogs#7]
I found, that for [PRNG approach](https://github.com/zhinst/blogs/blob/master/Randomized%20Benchmarking%20in%20Seconds/Randomized_Benchmarking_in_Seconds.ipynb) $m1$ values bigger than 200 cause the following error:
'_**Reinitialized signal output delay on channel 2 (numbered from 0)**_'

For this channel the waveform was played from command table. The conditions to reproduce it:
1) m1>200 in repeat loop,
2) executeTableEntry(waveform_index) in repeat loop,
3) getPRNGValue() in repeat loop.

I can also present any additional settings/sequencer code information if the above mentioned information is not enough.

**Comment by YakBizzarro** [comment]
dear @IVN-tone ,
thanks for the report. The issue seems a hardware issue, rather than a problem due to the sequence itself. Could you tell me the device serial number? Feel free to write me privately at Andrea.Corna@zhinst.com

**Comment by IVN-tone** [comment]
thank you for advice! you're right, it is gardware problem(( so, I close the issue.
